### ISSUE TITLE
如果源库是SQL，执行报错

### ISSUE THREAD

**Issue by eason0420** [Jawf/DataX-Migration#2]
2018-11-29 17:41:24,635 ERROR DruidDataSource:706 - {dataSource-1} init error
 java.sql.SQLException: com.microsoft.sqlserver.jdbc.SQLServerDriver
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:566)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:642)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:988)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:984)
        at com.yxt.data.migration.util.DbHelper.getSourceConnection(DbHelper.java:93)
        at com.yxt.data.migration.DbViewerImpl.getSourceTransfterTablesStatus(DbViewerImpl.java:113)
        at com.yxt.data.migration.JobJsonGenerator.generate(JobJsonGenerator.java:33)
        at com.yxt.data.migration.ApplicationBoot.main(ApplicationBoot.java:66)
Caused by: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:564)
        ... 7 more
2018-11-29 17:41:24,637  INFO DbHelper:97 - main Get Source connection failed!
 java.sql.SQLException: com.microsoft.sqlserver.jdbc.SQLServerDriver
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:566)
        at com.alibaba.druid.pool.DruidDataSource.init(DruidDataSource.java:642)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:988)
        at com.alibaba.druid.pool.DruidDataSource.getConnection(DruidDataSource.java:984)
        at com.yxt.data.migration.util.DbHelper.getSourceConnection(DbHelper.java:93)
        at com.yxt.data.migration.DbViewerImpl.getSourceTransfterTablesStatus(DbViewerImpl.java:113)
        at com.yxt.data.migration.JobJsonGenerator.generate(JobJsonGenerator.java:33)
        at com.yxt.data.migration.ApplicationBoot.main(ApplicationBoot.java:66)
Caused by: java.lang.ClassNotFoundException: com.microsoft.sqlserver.jdbc.SQLServerDriver
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at com.alibaba.druid.util.JdbcUtils.createDriver(JdbcUtils.java:564)
        ... 7 more
2018-11-29 17:41:24,638 ERROR ApplicationBoot:76 - 
 java.lang.NullPointerException
        at com.yxt.data.migration.DbViewerImpl.getSourceTransfterTablesStatus(DbViewerImpl.java:113)
        at com.yxt.data.migration.JobJsonGenerator.generate(JobJsonGenerator.java:33)
        at com.yxt.data.migration.ApplicationBoot.main(ApplicationBoot.java:66)
2018-11-29 17:41:24,639  INFO GenericXmlApplicationContext:862 - Closing org.springframework.context.support.GenericXmlApplicationContext@2530c12: startup date [Thu Nov 29 17:41:24 CST 2018]; root of context hierarchy

**Comment by eason0420** [comment]
pom中少了sql server驱动包
<dependency>
  <groupId>com.microsoft.sqlserver</groupId>
  <artifactId>mssql-jdbc</artifactId>
  <version>7.0.0.jre8</version>
</dependency>

**Comment by Jawf** [comment]
@eason0420 可以把sqlserver正确的pom依赖发个pull request提交过来：）
